name: RemixSite

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Run deploy script on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Ecommerce_Website
            sudo git reset --hard HEAD
            sudo git clean -fd
            sudo git pull origin main      
            sudo npm install

            # Check if PM2 process 'web' exists
            if pm2 describe web > /dev/null 2>&1; then
              echo "ğŸ” PM2 process 'web' exists. Restarting..."
              sudo pm2 restart web
            else
              echo "â–¶ï¸ PM2 process 'web' not found. Starting..."
              sudo pm2 start ./startup.sh --name "web" -- start
            fi
